# 01 - Data Understanding

## Tujuan

Notebook ini digunakan untuk memahami struktur, karakteristik,
dan kualitas awal dataset Customer Segmentation sebelum dilakukan
proses Data Cleaning dan RFM Analysis.

Analisis awal mencakup:

- struktur dataset
- ukuran dataset
- tipe data
- missing values
- duplicate
- unique values
- statistik deskriptif
- validasi awal data

In [3]:
import pandas as pd
c=pd.read_csv('../data/raw/customers.csv')
t=pd.read_csv('../data/raw/transactions.csv')
print(c.shape,t.shape)
print(t.isna().sum())
print('Duplicates:',t.duplicated().sum())

(2000, 6) (25025, 9)
transaction_id       0
customer_id          0
transaction_date     0
category             0
quantity             0
unit_price           0
discount_pct         0
revenue              0
payment_method      30
dtype: int64
Duplicates: 25

In [6]:
t.sample(5)

,transaction_id,customer_id,transaction_date,category,quantity,unit_price,discount_pct,revenue,payment_method
20566,TRX0020567,CUST01930,2025-02-04,Beauty,2,50000,40,60000,Credit Card
14155,TRX0014156,CUST02000,2024-04-29,Electronics,1,3167000,20,2533600,Virtual Account
12572,TRX0012573,CUST00493,2024-11-09,Food & Beverage,4,207000,15,703800,Bank Transfer
11190,TRX0011191,CUST00005,2024-03-04,Sports,1,89000,15,75650,Bank Transfer
21694,TRX0021695,CUST00044,2024-04-19,Fashion,1,99000,10,89100,E-Wallet

In [7]:
c.sample(5)

,customer_id,customer_name,gender,city,registration_date,province
947,CUST00948,Customer 0948,Female,Jakarta,2024-02-02,DKI Jakarta
1073,CUST01074,Customer 1074,Male,Yogyakarta,2025-12-22,DI Yogyakarta
1136,CUST01137,Customer 1137,Male,Jakarta,2024-05-04,DKI Jakarta
259,CUST00260,Customer 0260,Male,Bekasi,2024-11-04,Jawa Barat
1404,CUST01405,Customer 1405,Female,Tangerang,2023-04-18,Banten

## Dataset Grain

- `customers.csv`: satu baris merepresentasikan satu customer.
- `transactions.csv`: satu baris merepresentasikan satu transaksi.
- Kedua tabel dihubungkan menggunakan `customer_id`.

In [8]:
t.shape

(25025, 9)

In [9]:
c.shape

(2000, 6)

In [11]:
print("CUSTOMERS")
print(f"Rows    : {c.shape[0]:,}")
print(f"Columns : {c.shape[1]}")

print("\nTRANSACTIONS")
print(f"Rows    : {t.shape[0]:,}")
print(f"Columns : {t.shape[1]}")

CUSTOMERS
Rows    : 2,000
Columns : 6

TRANSACTIONS
Rows    : 25,025
Columns : 9

In [12]:
print(c.columns.tolist())

['customer_id', 'customer_name', 'gender', 'city', 'registration_date', 'province']

In [13]:
print(t.columns.tolist())

['transaction_id', 'customer_id', 'transaction_date', 'category', 'quantity', 'unit_price', 'discount_pct', 'revenue', 'payment_method']

In [14]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2000 non-null   object
 1   customer_name      2000 non-null   object
 2   gender             1992 non-null   object
 3   city               2000 non-null   object
 4   registration_date  2000 non-null   object
 5   province           2000 non-null   object
dtypes: object(6)
memory usage: 93.9+ KB

In [15]:
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25025 entries, 0 to 25024
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    25025 non-null  object
 1   customer_id       25025 non-null  object
 2   transaction_date  25025 non-null  object
 3   category          25025 non-null  object
 4   quantity          25025 non-null  int64
 5   unit_price        25025 non-null  int64
 6   discount_pct      25025 non-null  int64
 7   revenue           25025 non-null  int64
 8   payment_method    24995 non-null  object
dtypes: int64(4), object(5)
memory usage: 1.7+ MB

Cek Missing Value

In [18]:
c.isna().sum()

customer_id          0
customer_name        0
gender               8
city                 0
registration_date    0
province             0
dtype: int64

In [19]:
t.isna().sum()

transaction_id       0
customer_id          0
transaction_date     0
category             0
quantity             0
unit_price           0
discount_pct         0
revenue              0
payment_method      30
dtype: int64

In [20]:
def missing_report(df):
    report = pd.DataFrame({
        "missing_count": df.isna().sum(),
        "missing_percentage": (
            df.isna().sum() / len(df) * 100
        )
    })

    return report.sort_values(
        "missing_count",
        ascending=False
    )

In [22]:
missing_report(c)

                   missing_count  missing_percentage
gender                         8                 0.4
customer_id                    0                 0.0
customer_name                  0                 0.0
city                           0                 0.0
registration_date              0                 0.0
province                       0                 0.0

In [23]:
missing_report(t)

                  missing_count  missing_percentage
payment_method               30             0.11988
transaction_id                0             0.00000
customer_id                   0             0.00000
transaction_date              0             0.00000
category                      0             0.00000
quantity                      0             0.00000
unit_price                    0             0.00000
discount_pct                  0             0.00000
revenue                       0             0.00000

In [25]:
c.duplicated().sum()

np.int64(0)

In [26]:
t.duplicated().sum()

np.int64(25)

In [28]:
t[t.duplicated(keep=False)
].sort_values("transaction_id")

,transaction_id,customer_id,transaction_date,category,quantity,unit_price,discount_pct,revenue,payment_method
2227,TRX0002228,CUST01472,2024-03-14,Home & Living,1,368000,15,312800,COD
25023,TRX0002228,CUST01472,2024-03-14,Home & Living,1,368000,15,312800,COD
2518,TRX0002519,CUST00933,2024-03-26,Beauty,1,211000,30,147700,Bank Transfer
25014,TRX0002519,CUST00933,2024-03-26,Beauty,1,211000,30,147700,Bank Transfer
3386,TRX0003387,CUST01815,2024-01-26,Food & Beverage,1,19000,20,15200,Credit Card
25008,TRX0003387,CUST01815,2024-01-26,Food & Beverage,1,19000,20,15200,Credit Card
3503,TRX0003504,CUST01790,2025-08-07,Beauty,4,216000,25,648000,Credit Card
25011,TRX0003504,CUST01790,2025-08-07,Beauty,4,216000,25,648000,Credit Card
5804,TRX0005805,CUST01268,2024-06-15,Fashion,1,63000,10,56700,E-Wallet
25006,TRX0005805,CUST01268,2024-06-15,Fashion,1,63000,10,56700,E-Wallet
25018,TRX0006493,CUST00510,2025-10-18,Beauty,1,47000,5,44650,Virtual Account
6492,TRX0006493,CUST00510,2025-10-18,Beauty,1,47000,5,44650,Virtual Account
6649,TRX0006650,CUST01749,2024-12-30,Fashion,2,385000,15,654500,Virtual Account
25022,TRX0006650,CUST01749,2024-12-30,Fashion,2,385000,15,654500,Virtual Account
6657,TRX0006658,CUST01059,2025-03-26,Beauty,2,113000,30,158200,Credit Card
25012,TRX0006658,CUST01059,2025-03-26,Beauty,2,113000,30,158200,Credit Card
25000,TRX0006869,CUST00061,2025-11-10,Fashion,2,236000,15,401200,E-Wallet
6868,TRX0006869,CUST00061,2025-11-10,Fashion,2,236000,15,401200,E-Wallet
25019,TRX0006892,CUST00427,2024-03-04,Sports,2,382000,0,764000,COD
6891,TRX0006892,CUST00427,2024-03-04,Sports,2,382000,0,764000,COD
25005,TRX0007489,CUST01090,2024-01-05,Electronics,3,2680000,20,6432000,COD
7488,TRX0007489,CUST01090,2024-01-05,Electronics,3,2680000,20,6432000,COD
7752,TRX0007753,CUST01952,2025-04-26,Sports,1,102000,25,76500,E-Wallet
25020,TRX0007753,CUST01952,2025-04-26,Sports,1,102000,25,76500,E-Wallet
25021,TRX0008615,CUST01875,2024-03-16,Fashion,1,122000,0,122000,Credit Card
8614,TRX0008615,CUST01875,2024-03-16,Fashion,1,122000,0,122000,Credit Card
9567,TRX0009568,CUST00383,2025-04-10,Beauty,2,49000,20,78400,E-Wallet
25009,TRX0009568,CUST00383,2025-04-10,Beauty,2,49000,20,78400,E-Wallet
25002,TRX0009669,CUST01390,2024-07-05,Home & Living,4,592000,30,1657600,E-Wallet
9668,TRX0009669,CUST01390,2024-07-05,Home & Living,4,592000,30,1657600,E-Wallet
25024,TRX0012061,CUST01972,2025-07-26,Food & Beverage,3,43000,20,103200,Bank Transfer
12060,TRX0012061,CUST01972,2025-07-26,Food & Beverage,3,43000,20,103200,Bank Transfer
25007,TRX0012910,CUST00439,2025-12-03,Home & Living,1,855000,15,726750,E-Wallet
12909,TRX0012910,CUST00439,2025-12-03,Home & Living,1,855000,15,726750,E-Wallet
25015,TRX0013362,CUST00813,2024-07-09,Beauty,1,34000,0,34000,Credit Card
13361,TRX0013362,CUST00813,2024-07-09,Beauty,1,34000,0,34000,Credit Card
13640,TRX0013641,CUST01304,2024-09-28,Food & Beverage,1,58000,15,49300,Virtual Account
25003,TRX0013641,CUST01304,2024-09-28,Food & Beverage,1,58000,15,49300,Virtual Account
25004,TRX0014019,CUST01294,2024-07-01,Fashion,1,80000,25,60000,Bank Transfer
14018,TRX0014019,CUST01294,2024-07-01,Fashion,1,80000,25,60000,Bank Transfer
25013,TRX0019193,CUST00440,2025-02-23,Fashion,1,119000,25,89250,COD
19192,TRX0019193,CUST00440,2025-02-23,Fashion,1,119000,25,89250,COD
25017,TRX0021081,CUST00840,2024-03-26,Fashion,2,239000,20,382400,Virtual Account
21080,TRX0021081,CUST00840,2024-03-26,Fashion,2,239000,20,382400,Virtual Account
25016,TRX0021136,CUST01223,2025-11-30,Home & Living,3,81000,40,145800,Bank Transfer
21135,TRX0021136,CUST01223,2025-11-30,Home & Living,3,81000,40,145800,Bank Transfer
25010,TRX0021424,CUST01168,2025-03-31,Fashion,2,316000,5,600400,Virtual Account
21423,TRX0021424,CUST01168,2025-03-31,Fashion,2,316000,5,600400,Virtual Account
25001,TRX0024017,CUST01200,2025-02-05,Electronics,1,2010000,10,1809000,Virtual Account
24016,TRX0024017,CUST01200,2025-02-05,Electronics,1,2010000,10,1809000,Virtual Account

Unique Value

In [30]:
c.nunique()

customer_id          2000
customer_name        2000
gender                  2
city                   12
registration_date     929
province                8
dtype: int64

In [31]:
t.nunique()

transaction_id      25000
customer_id          1898
transaction_date      731
category                7
quantity                5
unit_price           2078
discount_pct            8
revenue              6635
payment_method          5
dtype: int64

Periksa categorical data

In [32]:
c["city"].value_counts(
    dropna=False
)

city
Jakarta       547
Bandung       265
Surabaya      239
Tangerang     199
Bekasi        167
Depok         141
Semarang      124
Makassar      115
Yogyakarta    108
Medan          79
BANDUNG         8
 jakarta        8
Name: count, dtype: int64

In [33]:
c["gender"].value_counts(
    dropna=False
)

gender
Male      1010
Female     982
NaN          8
Name: count, dtype: int64

In [34]:
t["category"].value_counts(
    dropna=False
)

category
Fashion            6920
Beauty             4536
Home & Living      3825
Electronics        3729
Food & Beverage    3472
Sports             2523
fashion              20
Name: count, dtype: int64

In [35]:
t["payment_method"].value_counts(
    dropna=False
)

payment_method
Bank Transfer      5056
Virtual Account    5002
COD                5001
Credit Card        4974
E-Wallet           4962
NaN                  30
Name: count, dtype: int64

Statistik numerik

In [36]:
t.describe()

           quantity    unit_price  discount_pct       revenue
count  25025.000000  2.502500e+04  25025.000000  2.502500e+04
mean       1.706134  3.204209e+05     12.274525  4.782462e+05
std        1.026832  4.791452e+05     10.453633  8.855634e+05
min        1.000000  1.500000e+04      0.000000  9.000000e+03
25%        1.000000  7.400000e+04      5.000000  9.180000e+04
50%        1.000000  1.590000e+05     10.000000  2.016000e+05
75%        2.000000  3.290000e+05     20.000000  4.675000e+05
max        5.000000  3.486000e+06     40.000000  1.327500e+07

Periksa range secara eksplisit

In [37]:
t[
    ["quantity", "unit_price", "discount_pct", "revenue"]
].agg(["min", "max", "mean", "median"])

        quantity    unit_price  discount_pct       revenue
min     1.000000  1.500000e+04      0.000000  9.000000e+03
max     5.000000  3.486000e+06     40.000000  1.327500e+07
mean    1.706134  3.204209e+05     12.274525  4.782462e+05
median  1.000000  1.590000e+05     10.000000  2.016000e+05

Validasi Business Rule — tetapi belum cleaning

In [39]:
t[
    t["quantity"] <= 0
]

Empty DataFrame
Columns: [transaction_id, customer_id, transaction_date, category, quantity, unit_price, discount_pct, revenue, payment_method]
Index: []

In [40]:
t[
    t["unit_price"] < 0
]

Empty DataFrame
Columns: [transaction_id, customer_id, transaction_date, category, quantity, unit_price, discount_pct, revenue, payment_method]
Index: []

In [41]:
t[
    ~t["discount_pct"].between(0, 100)
]

Empty DataFrame
Columns: [transaction_id, customer_id, transaction_date, category, quantity, unit_price, discount_pct, revenue, payment_method]
Index: []

In [42]:
t[
    t["revenue"] < 0
]

Empty DataFrame
Columns: [transaction_id, customer_id, transaction_date, category, quantity, unit_price, discount_pct, revenue, payment_method]
Index: []

In [43]:
expected_revenue = (
    t["quantity"]
    * t["unit_price"]
    * (1 - t["discount_pct"] / 100)
)

In [44]:
revenue_difference = (
    t["revenue"]
    - expected_revenue
).abs()

In [45]:
revenue_difference.describe()

count    2.502500e+04
mean     6.874726e-13
std      1.390519e-11
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      9.313226e-10
dtype: float64

In [48]:
quality_summary = pd.DataFrame({
    "column": t.columns,
    "dtype": t.dtypes.astype(str).values,
    "missing": t.isna().sum().values,
    "missing_pct": (
        t.isna().sum().values
        / len(t)
        * 100
    ),
    "unique": t.nunique().values
})

quality_summary

             column   dtype  missing  missing_pct  unique
0    transaction_id  object        0      0.00000   25000
1       customer_id  object        0      0.00000    1898
2  transaction_date  object        0      0.00000     731
3          category  object        0      0.00000       7
4          quantity   int64        0      0.00000       5
5        unit_price   int64        0      0.00000    2078
6      discount_pct   int64        0      0.00000       8
7           revenue   int64        0      0.00000    6635
8    payment_method  object       30      0.11988       5

# Data Understanding Summary

## Dataset Structure

Dataset terdiri dari dua tabel utama:

- `customers`: master data customer.
- `transactions`: data transaksi customer.

Relationship antara kedua tabel menggunakan `customer_id`.

## Grain

- Satu row pada `customers` merepresentasikan satu customer.
- Satu row pada `transactions` seharusnya merepresentasikan satu transaksi.

## Initial Data Quality Findings

Berdasarkan proses data profiling ditemukan beberapa hal yang
perlu diperiksa pada tahap Data Cleaning:

1. Terdapat duplicate pada dataset transaksi.
2. Beberapa categorical values tidak konsisten.
3. Terdapat missing values pada beberapa field.
4. Kolom tanggal belum memiliki tipe data datetime.
5. Terdapat beberapa nilai harga ekstrem yang memerlukan investigasi.
6. Validitas relationship customer dan transaksi telah diperiksa.

## Next Step

Masalah kualitas data yang ditemukan pada tahap ini akan
ditangani pada:

`02_data_cleaning.ipynb`